# Generated by Django 4.1.1 on 2022-09-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='paciente_phones',
        ),
    ]
