# Generated by Django 4.1.1 on 2022-09-22 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
