# Generated by Django 4.1.1 on 2022-09-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_paciente_paciente_phones'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='paciente_phones',
            field=models.ManyToManyField(through='project.PacientePhone', to='project.phone'),
        ),
    ]
