# Generated by Django 4.1.1 on 2022-09-22 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_delete_email_delete_paciente_delete_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PacientePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.DecimalField(decimal_places=1, max_digits=1)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('pacientes', models.ManyToManyField(through='project.PacientePhone', to='project.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='pacientephone',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.phone'),
        ),
    ]
