# Generated by Django 4.1.1 on 2022-09-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_phone_pacientes_paciente_paciente_phones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientephone',
            name='active',
            field=models.CharField(max_length=1),
        ),
    ]
