# Generated by Django 4.1.1 on 2022-09-23 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_pacientephone_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='phone',
            new_name='number',
        ),
    ]
