# Generated by Django 4.1.1 on 2022-09-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_rename_phone_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientephone',
            name='active',
            field=models.BooleanField(),
        ),
    ]
